name: Build minishell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: juliaattic/readline@6.2
    - name: build-minishell
      run: make

